#!/bin/bash
# config.sh - Carga de configuración del usuario

# Valores por defecto
CSM_CLEAN_DAYS=7
CSM_MAX_MESSAGES=500
CSM_AUTO_CLEAN_ENABLED=true
CSM_SHOW_TOOLS=true
# CSM_DATE_FORMAT="%Y-%m-%d %H:%M"  # Reserved for future use

# load_config - Cargar configuración desde archivo opcional
load_config() {
	local config_file="${1:-$HOME/.csmrc}"

	# Cargar configuración del usuario si existe
	if [ -f "$config_file" ]; then
		# shellcheck source=/dev/null
		source "$config_file"
	fi
}

# save_config - Guardar configuración actual
save_config() {
	local config_file="${1:-$HOME/.csmrc}"

	cat >"$config_file" <<EOF
# Claude Session Manager Configuration
# Generated by csm

CSM_CLEAN_DAYS=$CSM_CLEAN_DAYS
CSM_MAX_MESSAGES=$CSM_MAX_MESSAGES
CSM_AUTO_CLEAN_ENABLED=$CSM_AUTO_CLEAN_ENABLED
CSM_SHOW_TOOLS=$CSM_SHOW_TOOLS
EOF

	echo "Configuration saved to $config_file"
}
