#!/bin/bash
# help.sh - Mostrar ayuda

# cmd_help - Mostrar ayuda
cmd_help() {
	color_output "${BOLD}${CYAN}Claude Session Manager (csm)${NC}"
	echo ""
	color_output "${BOLD}${WHITE}USAGE:${NC}"
	color_output "    ${GREEN}csm${NC} <command> [options]"
	echo ""
	color_output "${BOLD}${WHITE}COMMANDS:${NC}"
	color_output "    ${GREEN}list${NC}                List all sessions"
	color_output "    ${GREEN}clean${NC}               Clean old sessions"
	color_output "    ${GREEN}remove${NC} <id>         Remove specific session"
	color_output "    ${GREEN}resume${NC} <id>         Show resume command for session"
	color_output "    ${GREEN}status${NC}              Show session statistics"
	color_output "    ${GREEN}help${NC}                Show this help message"
	echo ""
	color_output "${BOLD}${WHITE}OPTIONS:${NC}"
	echo ""
	color_output "  ${BOLD}list:${NC}"
	color_output "    ${CYAN}--all${NC}, ${CYAN}-a${NC}           Show all sessions including hidden"
	color_output "    ${CYAN}--current${NC}, ${CYAN}-c${NC}       Show only current session"
	echo ""
	color_output "  ${BOLD}clean:${NC}"
	color_output "    ${CYAN}--days${NC} N            Sessions older than N days (default: 7)"
	color_output "    ${CYAN}--force${NC}, ${CYAN}-f${NC}         Remove without confirmation"
	color_output "    ${CYAN}--dry-run${NC}, ${CYAN}-n${NC}       Show what would be removed"
	echo ""
	color_output "  ${BOLD}remove:${NC}"
	color_output "    ${CYAN}--force${NC}, ${CYAN}-f${NC}         Remove without confirmation"
	echo ""
	color_output "${BOLD}${WHITE}EXAMPLES:${NC}"
	color_output "    ${DIM}# List all sessions${NC}"
	color_output "    ${GREEN}csm${NC} list"
	color_output "    ${DIM}# Clean sessions older than 14 days${NC}"
	color_output "    ${GREEN}csm${NC} clean ${CYAN}--days${NC} 14"
	color_output "    ${DIM}# Remove session abc123${NC}"
	color_output "    ${GREEN}csm${NC} remove abc123"
	echo ""
	color_output "${BOLD}${WHITE}CONFIGURATION:${NC}"
	color_output "    Create ~/.csmrc with:"
	echo ""
	color_output "    ${CYAN}CSM_CLEAN_DAYS${NC}=7          ${DIM}# Days before clean${NC}"
	color_output "    ${CYAN}CSM_MAX_MESSAGES${NC}=500      ${DIM}# Max messages threshold${NC}"
	color_output "    ${CYAN}CSM_AUTO_CLEAN_ENABLED${NC}=1  ${DIM}# Enable auto-clean${NC}"
	echo ""
	color_output "${DIM}For more information, see: https://github.com/cativo23/claude-session-manager${NC}"
}
